### ISSUE TITLE
No “Go to filename data” link displayed

### ISSUE THREAD

**Issue by Uot** [TomCafferty/dokuwiki-plugin-eventline#4]
Hello Tom,

I 'm using dokuwiki release "Weatherwax RC1" and I installed Version 2013-03-06 of your eventline plugin. The keywords and tools plugin are installed and I changed the htaccess file to allow xml.

When I apply the syntax of the plugin in a dokuwiki-page, I get an empty timeline. But there is no “Go to filename data” link and the following message appears: "Failed to load data xml from …dokuwiki/lib/plugins/eventline/getData.php?id=test%3AZeitachse - Not Found"

On the plugin-site you wrote "the latest version updated 03/2013 only displays the goto filename link if the user has permission to edit the file". But I'm running dokuwiki as "admin". So I should have the permission to edit all files. I don't now if this is a bug? Maybe I made mistake with ht.access?

Uwe

**Comment by TomCafferty** [comment]
Hi Uwe,

You can get that "go to filename" back by making a small code change  
if you are comfortable with that. In the file

/eventline/syntax.php at line 172 simply comment out or delete the line

```
  if($info_writable)
```

My intent was to not have people that couldn't edit the file go to a  
page that looks kinda funny as the raw text.  There is no problem  
showing the link other than that.  I am running the previous version  
of dokuwiki. I will try an upgrade and see what happens. I run as  
admin and I see the link.

Best Regards
Tom

Quoting Uot notifications@github.com:

**Comment by Uot** [comment]
Hello Tom,

that works. I got that "go to filename" link. Thank you for your quick reply.

But there is still that message "Failed to load data xml from …dokuwiki/lib/plugins/eventline/getData.php?id=test%3AZeitachse - Not Found". And when I paste some data in that generated txt-file, my timeline remains empty. I have no idea, whats going on...

Best regards

Uwe

**Comment by TomCafferty** [comment]
Hi Uwe,

It is normal to get that error until the file is first created. Part  
of the process is that when you create or edit the text file it must  
then be exported as an xml file. The Tools plugin is used to do that.  
I add the Tools plugin syntax of ~~TOOLS:both~~ in the data text file  
page at the bottom after the end of the timeline events section like

[/event]
[/data]
~~TOOLS:both~~

  Then after you save the text file you should have a Tools icon on  
the page. Select export to timeline. Then see if the timeline has  
data.  When you look in the /data/pages folder for that timeline page  
you should see a .txt and .xml file

Regards
Tom

Quoting Uot notifications@github.com:

**Comment by TomCafferty** [comment]
Hi Uwe,
I an update to allow turning on or off the link to the datafile by  
using a conf setting. The new version defaults to showing the link.  
If you set conf['showlink'] = 'off' in the /conf/default.php file then  
it should only show the link if the user has permission to edit the  
file and write to that folder.
Tom

Quoting tcafferty@glocalfocal.com:

**Comment by Uot** [comment]
```
Hi Tom,
  now I see! My timeline is working. Many thanks for your plugin and
  your help.
  With best regards
  Uwe
  Am 11.04.2013 01:15, schrieb Tom Cafferty:
Hi Uwe,
  I an update to allow turning on or off the link to the datafile by

  using a conf setting. The new version defaults to showing the
  link. 
  If you set conf['showlink'] = 'off' in the /conf/default.php file
  then 
  it should only show the link if the user has permission to edit
  the 
  file and write to that folder.
  Tom
  Quoting tcafferty@glocalfocal.com:
  >
  > Hi Uwe,
  >
  > It is normal to get that error until the file is first
  created. Part 
  > of the process is that when you create or edit the text file
  it must 
  > then be exported as an xml file. The Tools plugin is used to
  do 
  > that. I add the Tools plugin syntax of ~~TOOLS:both~~ in the
  data 
  > text file page at the bottom after the end of the timeline
  events 
  > section like
  >
  > [/event]
  > [/data]
  > ~~TOOLS:both~~
  >
  > Then after you save the text file you should have a Tools
  icon on 
  > the page. Select export to timeline. Then see if the timeline
  has 
  > data. When you look in the /data/pages folder for that
  timeline 
  > page you should see a .txt and .xml file
  >
  > Regards
  > Tom
  >
  > Quoting Uot <notifications@github.com>:
  >
  >> Hello Tom,
  >>
  >> that works. I got that "go to filename" link. Thank you
  for your 
  >> quick reply.
  >>
  >> But there is still that message "Failed to load data xml
  from 
  >>
  …dokuwiki/lib/plugins/eventline/getData.php?id=test%3AZeitachse -

  >> Not Found". And when I paste some data in that generated
  txt-file, 
  >> my timeline remains empty. I have no idea, whats going
  on...
  >>
  >> Best regards
  >>
  >> Uwe
  >>
  >>
  >> ---
  >> Reply to this email directly or view it on GitHub:
  >>
```

https://github.com/TomCafferty/dokuwiki-plugin-eventline/issues/4#issuecomment-16172928
      >>
      >
      >
      >
      —
        Reply to this email directly or view
          it on GitHub.

```
-- 
```

Uwe Ottens
Czeminskistr. 1A
10829 Berlin

Tel. 030 | 69816028
Fax  030 | 69815398
Web  www.uwe-ottens.de

**Comment by TomCafferty** [comment]
This issue appears resolved.
