### ISSUE TITLE
meta info not created?

### ISSUE THREAD

**Issue by splitbrain** [TomCafferty/dokuwiki-plugin-eventline#6]
The javascript is only included when a certain meta data key for the page is present. However it seems this meta data is never created. I don't see any handling of the meta data renderer in syntax.php and in fact I only got it to work when removing the meta data check in action.php

**Comment by TomCafferty** [comment]
Hi,
The meta data would be created by the user by using the keywords plugin. The plugin page says the following:
     This plugin requires the following minimum syntax.
          <eventline>&file=filename&</eventline>
          {{keywords>timeline}}
I use that to not have the javascript included on every page when the eventline plugin is enabled. Maybe I do not understand this correctly but it seemed that if enabled the action class would execute and include the javascript even if not using eventline on a page.  I was never keen on requiring the keywords plugin. If I was wrong in my assumption or there is a better way to only include the javascript when needed let me know.
Thanks
Tom

**Comment by TomCafferty** [comment]
Thanks for the code changes. I put them in and they work great! I was able to remove that dependency on the other plugin :-)
