### ISSUE TITLE
XML loading is a security issue

### ISSUE THREAD

**Issue by splitbrain** [TomCafferty/dokuwiki-plugin-eventline#8]
The plugin's documentation describes how to disable the .htaccess protection for XML files in the data directory. This effectively disables any ACL protection for any uploaded XML file. Which is not recommended and can be a severe security hole when either timelines or other XML documents contain sensitive data.

Additionally this will break when the data directory has been moved out of the webserver root as recommended in the security precautions documentation.

The plugin should instead construct proper URLs for accessing XML documents via DokuWiki's `fetch.php` by using the `ml()` function.

**Comment by TomCafferty** [comment]
The documentation on  using .htaccess to allow access to XML files was removed from the plugin description page. Also the sample htaccess file was removed from the github commit.  It turned out that the code did not actually need this to work.
