### ISSUE TITLE
Plugin uses inline JavaScript, global namespace

### ISSUE THREAD

**Issue by splitbrain** [TomCafferty/dokuwiki-plugin-eventline#9]
This plugin creates inline JavaScript calls in the syntax component and also overwrites the window.onload method without taking care of any possibly existing window.onload handlers.

The plugin should instead attach handlers using jQuery's event methods.

In addition the loaded JavaScript add very generic functions (like onLoad) to the global JavaScript scope, which is prone to lead to conflicts with other scripts. The functionionality should be wrapped in some unique object or an anonymous function instead.

Please refer to https://www.dokuwiki.org/devel:javascript for JavaScript coding guidelines.

**Comment by TomCafferty** [comment]
I renamed the onLoad function to use the plugin name. I also used the following jQuery method to invoke the javascript from an event handler.

```
    $str .= "jQuery('#plugin_eventline').bind('load', plugin_eventline());";
    $str .= "jQuery('#plugin_eventline').bind('resize', plugin_eventline_onResize());";
```

Thanks for pointing out those issues.
Tom
